spring.application.name=oskar_game

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://${CLOUDRON_POSTGRESQL_HOST}/${CLOUDRON_POSTGRESQL_DATABASE}
spring.datasource.username=${CLOUDRON_POSTGRESQL_USERNAME}
spring.datasource.password=${CLOUDRON_POSTGRESQL_PASSWORD}

# create and drop table, good for testing, production set to none or comment it
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO}
spring.sql.init.mode=${SPRING_SQL_INIT_MODE}
spring.jpa.defer-datasource-initialization=true
spring.sql.init.data-locations=classpath:data.sql

management.endpoint.health.probes.enabled=true
management.endpoint.health.show-details=always
management.endpoints.web.exposure.include=health

configuration.allow-origin=${ALLOW_ORIGIN}

server.port=8080