INSERT INTO years(year, oscar_ceremony) values
(2026, '98e Cérémonie des Oscars'),
(2025, '97e Cérémonie des Oscars');

INSERT INTO movies(movieId, year_id, original_title, title) values
(1, 1, 'Bugonia', ''),
(2, 1, 'Sirat', 'Sirât'),
(3, 1, 'Sentimental Value', 'Valeur Sentimentale'),
(4, 1, 'Smashing Machine', 'The Smashing Machine'),
(5, 1, 'One Battle After Another', 'Une Bataille Après L''Autre'),
(6, 1, 'Is this thing on', ''),
(7, 1, 'Sinners', ''),
(8, 1, 'Frankenstein', ''),
(9, 1, 'F1', 'F1, Le Film'),
(10, 1, 'Hamnet', ''),
(11, 1, 'Blue Moon', ''),
(12, 1, 'Avatar Fire And Ash', 'Avatar : De Feu Et De Cendres'),
(13, 1, 'Kpop Demon Hunters', 'K-Pop Demon Hunters'),
(14, 1, 'The Perfect Neighbor', 'La Voisine Idéale'),
(15, 1, 'All The Empty Rooms', 'Toutes Les Chambres Vides'),
(16, 1, 'Retirement Plan', ''),
(17, 1, 'Marty Supreme', ''),
(18, 1, 'The Secret Agent', 'L''Agent Secret'),
(19, 1, 'Train Dreams', ''),
(20, 1, 'A Simple Accident', 'Un Simple Accident'),
(21, 1, 'Song Sung Blue', 'Sur Un Air De Blues'),
(22, 1, 'If I Had Legs I''d Kick You', ''),
(23, 1, 'Weapons', 'Évanouis'),
(24, 1, 'The Ugly Stepsister', ''),
(25, 1, 'Kokuho','Le Maitre Du Kabuki'),
(26, 1, 'Sawt Hind Rajab', 'La Voix De Hind Rajab'),
(27, 1, 'Amelie And The Character Of The Rain', 'Amélie Et La Métaphysique Des Tubes'),
(28, 1, 'Zootopie 2', ''),
(29, 1, 'Arco', ''),
(30, 1, 'Elio', ''),
(31, 1, 'Diane Warren: Relentless', 'Relentless'),
(32, 1, 'The Lost Bus', 'The Lost Bus - Au Coeur Des Flammes'),
(33, 1, 'Jurassic World: Rebirth', 'Jurassic World: Renaissance'),
(34, 1, 'Come See Me In The Good Light', ''),
(35, 1, 'The Alabama Solution', 'The Alabama Solution - Dans L''Enfer De La Prison'),
(36, 1, 'Cutting Through Rocks', ''),
(37, 1, 'Mister Nobody Against Putin', 'Mister Nobody Contre Poutine'),
(38, 1, 'A Friend Of Dorothy', ''),
(39, 1, 'Jane Austen''s Period Drame', 'Jane Austen’s Period Drama'),
(40, 1, 'Butterfly', ''),
(41, 1, 'Forevergreen', ''),
(42, 1, 'Perfectly A Strangeness', 'Une Parfaite Étrangeté'),
(43, 1, 'Viva Verdi !', ''),
(44, 1, 'All The empty Rooms', ''),
(45, 1, 'Armed Only with a camera : the life and death of Brent Renaud', ''),
(46, 1, 'Children no more : « Were and are Gone »', ''),
(47, 1, 'The Devil is Busy', ''),
(48, 1, 'Butcher’s Stain', ''),
(49, 1, 'The Singers', ''),
(50, 1, 'Two People Exchanging Saliva', ''),
(51, 1, 'The Girl Who Cried Pearls', ''),
(52, 1, 'The Three Sisters', '');

INSERT INTO categories(categoryId, year_id, name) values
(1, 1, 'Meilleur Film'),
(2, 1, 'Meilleur Réalisateur'),
(3, 1, 'Meilleur Acteur'),
(4, 1, 'Meilleure Actrice'),
(5, 1, 'Meilleur Acteur dans un Second Rôle'),
(6, 1, 'Meilleure Actrice dans un Second Rôle'),
(7, 1, 'Meilleur Scénario Original'),
(8, 1, 'Meilleur Scénario Adapté'),
(9, 1, 'Meilleur Décord Et Direction Artistique'),
(10, 1, 'Meilleurs Costumes'),
(11, 1, 'Meilleurs Maquillages Et Coiffures'),
(12, 1, 'Meilleure Photographie'),
(13, 1, 'Meilleur Montage'),
(14, 1, 'Meilleur Son'),
(15, 1, 'Meilleurs Effets Visuels'),
(16, 1, 'Meilleure Chanson Originale'),
(17, 1, 'Meilleure Musique De Film'),
(18, 1, 'Meilleur Film International'),
(19, 1, 'Meilleur Film D''Animation'),
(20, 1, 'Meilleur Film Documentaire'),
(21, 1, 'Meilleur Film Court Métrage Documentaire'),
(22, 1, 'Meilleur Film Court Métrage'),
(23, 1, 'Meilleur Film Court Métrage D''Animation'),
(24, 1, 'Meilleure Distribution');

INSERT INTO movie_items(won, category_id, movie_id, nominee) values
(false, 1, 1, 'Bugonia'),
(false, 1, 9, 'F1'),
(false, 1, 8, 'Frankenstein'),
(false, 1, 10, 'Hamnet'),
(false, 1, 17, 'Marty Supreme'),
(false, 1, 5, 'Une bataille après l''autre'),
(false, 1, 18, 'L''agent secret'),
(false, 1, 3, 'Valeur sentimentale'),
(false, 1, 7, 'Sinners'),
(false, 1, 19, 'Train Dreams'),

(false, 4, 10, 'Jessie Buckley'),
(false, 4, 22, 'Rose Byrne'),
(false, 4, 21, 'Kate Hudson'),
(false, 4, 3, 'Renate Reinsve'),
(false, 4, 1, 'Emma Stone'),

(false, 3, 17, 'Timothée Chalamet'),
(false, 3, 5, 'Leonardo DiCaprio'),
(false, 3, 11, 'Ethan Hawke'),
(false, 3, 7, 'Michael B. Jordan'),
(false, 3, 18, 'Wagner Moura'),

(false, 6, 3, 'Elle Fanning'),
(false, 6, 3, 'Inga Ibsdotter Lilleass'),
(false, 6, 23, 'Amy Madigan'),
(false, 6, 7, 'Wunmi Mosaku'),
(false, 6, 5, 'Teyana Taylor'),

(false, 5, 5, 'Benicio del Toro'),
(false, 5, 8, 'Jacob Elordi'),
(false, 5, 7, 'Delroy Lindo'),
(false, 5, 5, 'Sean Penn'),
(false, 5, 3, 'Stellan Skarsgaard'),

(false, 2, 10, 'Chloe Zhao'),
(false, 2, 17, 'Josh Sadie'),
(false, 2, 5, 'Paul Thomas Anderson'),
(false, 2, 3, 'Joachim Trier'),
(false, 2, 7, 'Ryan Coogler'),

(false, 24, 10, 'Hamnet'),
(false, 24, 17, 'Marty Supreme'),
(false, 24, 5, 'Une bataille après l''autre'),
(false, 24, 18, 'L''agent secret'),
(false, 24, 7, 'Sinners'),

(false, 7, 11, 'Blue Moon, de Robert Kaplow'),
(false, 7, 20, 'Un simple accident, de Jafar Panahi'),
(false, 7, 17, 'Marty Supreme, de Ronald Bronstein et Josh Safdie'),
(false, 7, 3, 'Valeur sentimentale, d’Eskil Vogt et Joachim Trier'),
(false, 7, 7, 'Sinners, de Ryan Coogler'),

(false, 8, 1, 'Bugonia, de Will Tracy'),
(false, 8, 8, 'Frankenstein, de Guillermo del Toro'),
(false, 8, 10, 'Hamnet, de Chloé Zhao et Maggie O’Farrell'),
(false, 8, 5, 'Une bataille après l’autre, de Paul Thomas Anderson'),
(false, 8, 19, 'Train dreams, de Clint Bentley et Greg Kwedar'),

(false, 19, 29, 'Arco'),
(false, 19, 30, 'Elio'),
(false, 19, 13, 'K-Pop Demon Hunters'),
(false, 19, 27, 'Amélie et la Métaphysique des tubes'),
(false, 19, 28, 'Zootopie 2'),

(false, 18, 18, 'L''agent secret (Brésil)'),
(false, 18, 20, 'Un simple accident (France)'),
(false, 18, 3, 'Valeur sentimentale (Norvège)'),
(false, 18, 2, 'Sirât (Espagne)'),
(false, 18, 26, 'La voix d''Hind Rajab (Tunisie)'),

(false, 12, 8, 'Frankenstein, Dan Laustsen'),
(false, 12, 17, 'Marty Supreme, Darius Khondji'),
(false, 12, 5, 'Une bataille après l’autre, Michaël Bauman'),
(false, 12, 7, 'Sinners, Autumn Durald Arkapaw'),
(false, 12, 19, 'Train Dreams, Adolpho Veloso'),

(false, 9, 8, 'Frankenstein'),
(false, 9, 10, 'Hamnet'),
(false, 9, 17, 'Marty Supreme'),
(false, 9, 5, 'Une bataille après l''autre'),
(false, 9, 7, 'Sinners'),

(false, 10, 12, 'Avatar : de Feu et de cendres'),
(false, 10, 8, 'Frankenstein'),
(false, 10, 10, 'Hamnet'),
(false, 10, 17, 'Marty Supreme'),
(false, 10, 7, 'Sinners'),

(false, 11, 8, 'Frankenstein'),
(false, 11, 25, 'Kokuho'),
(false, 11, 7, 'Sinners'),
(false, 11, 4, 'The Smashing Machine'),
(false, 11, 24, 'The Ugly Stepsister'),

(false, 13, 9, 'F1'),
(false, 13, 17, 'Marty Supreme'),
(false, 13, 5, 'Une bataille après l''autre'),
(false, 13, 3, 'Valeur sentimentale'),
(false, 13, 7, 'Sinners'),

(false, 14, 9, 'F1'),
(false, 14, 8, 'Frankenstein'),
(false, 14, 5, 'Une bataille après l’autre'),
(false, 14, 7, 'Sinners, par Chris Welcker, Benjamin A. Burtt'),
(false, 14, 2, 'Sirât'),

(false, 15, 12, 'Avatar : De feu et de cendres'),
(false, 15, 9, 'F1'),
(false, 15, 33, 'Jurassic World : Renaissance'),
(false, 15, 32, 'The Lost Bus : Au cœur des flammes'),
(false, 15, 7, 'Sinners'),

(false, 17, 1, 'Jerskin Fendrix'),
(false, 17, 8, 'Alexandre Desplat'),
(false, 17, 10, 'Max Richter'),
(false, 17, 5, 'Jonny Greenwood'),
(false, 17, 7, 'Ludwig Goransson'),

(false, 16, 31, '« Dear Me »'),
(false, 16, 13, '« Golden »'),
(false, 16, 7, '« I Lied To You »'),
(false, 16, 43, '« Sweet Dreams Of Joy »'),
(false, 16, 19, '« Train Dreams »'),

(false, 20, 35, 'The Alabama Solution'),
(false, 20, 34, 'Come See Me in the Good Light'),
(false, 20, 36, 'Cutting Through Rocks'),
(false, 20, 37, 'Mr. Nobody against Putin'),
(false, 20, 14, 'La Voisine idéale (The Perfect Neighbor)'),

(false, 21, 44, 'All The empty Rooms'),
(false, 21, 45, 'Armed Only with a camera : the life and death of Brent Renaud'),
(false, 21, 46, 'Children no more : « Were and are Gone »'),
(false, 21, 47, 'The Devil is Busy'),
(false, 21, 42, 'Perfectly a strangeness'),

(false, 22, 48, 'Butcher’s Stain'),
(false, 22, 49, 'The Singers'),
(false, 22, 38, 'A Friend of Dorothy'),
(false, 22, 39, 'Jane Austen’s Period Drama'),
(false, 22, 50, 'Two People Exchanging Saliva'),

(false, 23, 40, 'Butterfly'),
(false, 23, 41, 'Forevergreen'),
(false, 23, 51, 'The Girl Who Cried Pearls'),
(false, 23, 16, 'Retirement Plan'),
(false, 23, 52, 'The Three Sisters');
