INSERT INTO years(year, oscar_ceremony) values
(2026, '98e Cérémonie des Oscars'),
(2025, '97e Cérémonie des Oscars');

INSERT INTO movies(year_id, original_title, title) values
(1, 'Bugonia', ''),
(1, 'Sirat', ''),
(1, 'Sentimental Value', 'Valeur Sentimentale'),
(1, 'Smashing Machine', 'The Smashing Machine'),
(1, 'One Battle After Another', 'Une Bataille Après L''Autre'),
(1, 'Is this thing on', ''),
(1, 'Sinners', ''),
(1, 'Frankenstein', ''),
(1, 'F1', 'F1, Le Film'),
(1, 'Hamnet', ''),
(1, 'Blue Moon', ''),
(1, 'Avatar Fire And Ash', 'Avatar : De Feu Et De Cendres'),
(1, 'Kpop Demon Hunters', ''),
(1, 'The Perfect Neighbor', 'La Voisine Idéale'),
(1, 'All The Empty Rooms', 'Toutes Les Chambres Vides'),
(1, 'Retirement Plan', ''),
(1, 'Marty Supreme', ''),
(1, 'The Secret Agent', 'L''Agent Secret'),
(1, 'Train Dreams', ''),
(1, 'A Simple Accident', 'Un Simple Accident'),
(1, 'Song Sung Blue', 'Sur Un Air De Blues'),
(1, 'If I Had Legs I''d Kick You', ''),
(1, 'Weapons', 'Évanouis'),
(1, 'The Ugly Stepsister', ''),
(1, 'Kokuho','Le Maitre Du Kabuki'),
(1, 'Sawt Hind Rajab', 'La Voix De Hind Rajab'),
(1, 'Amelie And The Character Of The Rain', 'Amélie Et La Métaphysique Des Tubes'),
(1, 'Zootopie 2', ''),
(1, 'Arco', ''),
(1, 'Elio', ''),
(1, 'Diane Warren: Relentless', ''),
(1, 'The Lost Bus', 'The Lost Bus - Au Coeur Des Flammes'),
(1, 'Jurassic World: Rebirth', 'Jurassic World: Renaissance'),
(1, 'Come See Me In The Good Light', ''),
(1, 'The Alabama Solution', 'The Alabama Solution - Dans L''Enfer De La Prison'),
(1, 'Cutting Through Rocks', ''),
(1, 'Mister Nobody Against Putin', 'Mister Nobody Contre Poutine'),
(1, 'A Friend Of Dorothy', ''),
(1, 'Jane Austen''s Period Drame', ''),
(1, 'Papillon', ''),
(1, 'Forevergreen', ''),
(1, 'Perfectly A Strangeness', 'Une Parfaite Étrangeté');

INSERT INTO categories(year_id, name) values
(1, 'Meilleur Film'),
(1, 'Meilleur Réalisateur'),
(1, 'Meilleur Acteur'),
(1, 'Meilleure Actrice'),
(1, 'Meilleur Acteur dans un Second Rôle'),
(1, 'Meilleure Actrice dans un Second Rôle'),
(1, 'Meilleur Scénario Original'),
(1, 'Meilleur Scénario Adapté'),
(1, 'Meilleur Décord Et Direction Artistique'),
(1, 'Meilleurs Costumes'),
(1, 'Meilleurs Maquillages Et Coiffures'),
(1, 'Meilleure Photographie'),
(1, 'Meilleur Montage'),
(1, 'Meilleur Son'),
(1, 'Meilleurs Effets Visuels'),
(1, 'Meilleure Chanson Originale'),
(1, 'Meilleure Musique De Film'),
(1, 'Meilleur Film International'),
(1, 'Meilleur Film D''Animation'),
(1, 'Meilleur Film Documentaire'),
(1, 'Meilleur Film Court Métrage Documentaire'),
(1, 'Meilleur Film Court Métrage'),
(1, 'Meilleur Film Court Métrage D''Animation'),
(1, 'Meilleure Distribution');

-- INSERT INTO movie_items(won, category_id, movie_id, nominee) values ();
